Remove build context
NethermindEth/mock-avs-pkg pull request #10
Opened 2023-08-25 10:39 UTC by adriantpaez

Remove build context from docker-compose files. The services' source code are stored in the mock-avs-src repository, where the user can find the instructions to build the services images.

2023-08-25 11:50 UTC, AntiD2ta requested changes

2023-08-25 11:50 UTC, AntiD2ta commented on pkg/health-checker/docker-compose.yml
> +    image: mock-avs-health-checker:latest
Use env variables for this as that's the recommended best practice from us

2023-08-25 11:50 UTC, AntiD2ta commented on pkg/option-returner/docker-compose.yml
> +    image: mock-avs-option-returner:latest
Same here

2023-08-28 07:19 UTC, adriantpaez commented on pkg/health-checker/docker-compose.yml
> +    image: mock-avs-health-checker:latest
Done https://github.com/NethermindEth/mock-avs/pull/10/commits/95bade5bcca5c53db1deeb22a7c0dcb24b4effdb

2023-08-28 07:19 UTC, adriantpaez commented on pkg/option-returner/docker-compose.yml
> +    image: mock-avs-option-returner:latest
Done https://github.com/NethermindEth/mock-avs/pull/10/commits/95bade5bcca5c53db1deeb22a7c0dcb24b4effdb

2023-08-28 09:44 UTC, AntiD2ta approved these changes

2023-08-28 09:44 UTC, merged