Update mock AVS
NethermindEth/mock-avs-pkg pull request #4
Opened 2023-07-05 08:35 UTC by AntiD2ta

## Changes:

- [Add json-rpc method metric to option-returner](https://github.com/NethermindEth/mock-avs/commit/2e4482140c08e6ede4f53209645508a21b93804c)
- [Add health-checker profile](https://github.com/NethermindEth/mock-avs/commit/9b036d71ee6393c2e7940a4ad5256fa4f03bacee)
- [Add plugin](https://github.com/NethermindEth/mock-avs/commit/f8a27a2103e2099e36c35e89edf5c70cff7f3486)

2023-07-05 09:31 UTC, smartprogrammer93 approved these changes

2023-07-05 12:16 UTC, adriantpaez commented on pkg/manifest.yml
> +  - git: https://github.com/NethermindEth/mock-avs.git#main:plugin
Is the plugin the same repo as the mock-avs, the same Python server? What means the `#main:plugin` at the end? I tried to clone it but got the following error:
![image](https://github.com/NethermindEth/mock-avs/assets/44682532/c891cd4b-529c-4c3c-a1be-937dfcb6ec0d)

2023-07-06 09:27 UTC, adriantpaez requested changes

2023-07-06 09:27 UTC, adriantpaez commented on pkg/manifest.yml
> +  - git: https://github.com/NethermindEth/mock-avs.git#main:plugin
We are supporting only one plugin per package, remove the `-` to avoid managing `plugin` as a YAML list
```suggestion
    git: https://github.com/NethermindEth/mock-avs.git#main:plugin
```

2023-07-06 12:43 UTC, AntiD2ta commented on pkg/manifest.yml
> +  - git: https://github.com/NethermindEth/mock-avs.git#main:plugin
Done [f5fc91a](https://github.com/NethermindEth/mock-avs/pull/4/commits/f5fc91aaea451487a7b61d70ac873827161aa78c)

2023-07-06 12:43 UTC, AntiD2ta commented on pkg/manifest.yml
> +  - git: https://github.com/NethermindEth/mock-avs.git#main:plugin
Done [f5fc91a](https://github.com/NethermindEth/mock-avs/pull/4/commits/f5fc91aaea451487a7b61d70ac873827161aa78c)

2023-07-06 13:17 UTC, smartprogrammer93 approved these changes

2023-07-06 14:03 UTC, merged