chore: add compliant hardware requirements to manifest
NethermindEth/mock-avs-pkg pull request #5
Opened 2023-07-13 14:21 UTC by krafugo

2023-07-13 14:22 UTC, krafugo commented
This PR is for creating a tag version with compliant hardware requirements

2023-07-21 13:32 UTC, AntiD2ta approved these changes

2023-07-21 13:33 UTC, AntiD2ta requested changes
Solve conflicts in the checksum

2023-07-21 15:53 UTC, AntiD2ta approved these changes

2023-07-21 15:53 UTC, merged